language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_script:
    - composer self-update
    - composer install --dev

script:
    - mkdir -p build/logs
    - make sniff test

after_script:
    - CODECLIMATE_REPO_TOKEN=15414484551ad327593cb7feb55d0e08bdd3409054111068b40215a8504232da ./vendor/bin/test-reporter
